name: build-and-test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Set up Kind
        uses: helm/kind-action@v1.8.0

      - name: Install pre-commit
        run: |
          pip install pre-commit

      - name: Run pre-commit checks
        run: pre-commit run --all-files

      - name: Run build/test pipeline
        run: make all

      - name: Verify kubectl_aliases is up-to-date
        run: |
          git diff --exit-code kubectl_aliases || (
            echo "::error::kubectl_aliases is outdated. Run 'make all' and commit the file."
            exit 1
          )
